config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#index'
  devise_for :users
  resources :users
  

  resources :bets,     only: [ :show, :create ]
  resources :cashouts, only: [ :create ]
  resources :transactions, only: [ :index ]
  
  get 'configuration' => 'visitors#configure'
  
  get "/bet_table" => "visitors#bet_table"
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    session[:server_seed] = SecureRandom.hex(12)

    respond_to do |format|
      format.html do
        @bet  = Bet.new.tap do |b|
          b.server_seed = session[:server_seed]
          b.amount      = 0
          b.game        = 49.5
        end
        
        @cashout = Cashout.new
        
        @transactions = []

        @bets = Bet.latest_bets
        @data_slider_range = "0,0"
        
        if current_user
          
          setup_transactions 
          
          make_sure_user_address_is_set
          
          last_bet = current_user.bets.last
          if last_bet != nil and last_bet.amount < current_user.balance
            @bet.amount = last_bet.amount
            @bet.game = last_bet.game
          end
          
          @data_slider_range = "0," + current_user.balance.to_s
          
          @qr = RQRCode::QRCode.new(current_user.bitcoin_address)
        end
      end
      format.json do
        attrs = { server_seed: session[:server_seed] }
        attrs.merge!(auth_token: current_user.auth_token) if current_user
        
        render json: attrs
      end
    end
  end
  
  def bet_table
        
    respond_to do |format|
      format.html do
        @bets = Bet.latest_bets
        render :layout => false
      end
    end    
  end
  
  def make_sure_user_address_is_set
    if current_user.bitcoin_address == nil
      keys = ColdStorage.get_extended_keys
      current_user.bitcoin_address = OnChain::Sweeper.multi_sig_address_from_mpks(
        keys.length, keys, "m/#{current_user.id}")
      current_user.save
    end
  end
  
  def setup_transactions
    
    balances = current_user.balances.all
    
    @transactions = []
    
    balances.each do |balance|
      if ! balance.transaction_hash.start_with? "Bet"
        if ! balance.transaction_hash.start_with? "Cashout"
          tx = {}
          tx[:amount] = balance.amount / 100000000.0
          tx[:address] = "Deposit"
          tx[:status] = "Processed"
          tx[:date] = balance.created_at
          @transactions << tx
        else
          tx = {}
          tx[:amount] = balance.amount / 100000000.0
          tx[:address] = balance.transaction_hash
          tx[:status] = "Awaiting Signoff"
          tx[:date] = balance.created_at
          @transactions << tx
        end
      end
    end
  end
  
  # We get here if our ENV vars are not set.
  def configure
  end
  
end

app/views/visitors/_bets_table_rows.html.haml
- @bets.each do |bet|
  - begin
    %tr
      %td.text-primary
        = link_to bet.id.to_s, bet_url(bet), { onclick: 'showVerification("' + bet.id.to_s + '"); return false' }
      %td
        = bet.user.name
      %td
        = time_ago_in_words(bet.created_at)
        ago.
      %td
        = bet.amount_formatted
      %td
        = bet.multiplier.round(2)
      %td
        - if bet.rolltype == 'under'
          <
        - else
          >
        = bet.game
      %td
        = bet.roll
      %td
        - if bet.win? or bet.amount == 0
          %span.label.label-success
            = bet.profit_formatted
        - else
          %span.label.label-default
            = bet.profit_formatted
  - rescue => e
    - puts e

app/views/visitors/_cashout_modal.html.haml
#cashoutModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span.aria-hidden
            &times;
          %span.sr-only
            Close
        %h4.modal-title Cashout
        %p Please note a fee of 0.0005 BTC will be taken from your balance.
      .modal-body
        = form_for(@cashout, html: { role: 'form', class: 'inline-form', id: 'cashoutForm' }) do |f|
          .row
            .col-md-12
              %label Address

              = f.text_field :address, class: 'form-control', id: 'address'
            .col-md-12
              %label Amount
              = f.text_field :amount, class: 'form-control', id: 'amount'
            .col-md-12
              %input.btn.btn-primary#cashout-button{:style => "margin-top: 10px", :type => "submit", :value => "Cashout"}/

app/views/visitors/_deposit_modal.html.haml
#depositModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span.aria-hidden
            &times;
          %span.sr-only
            Close
        %h4.modal-title Deposit
      .modal-body
        %p.center-block Please send funds to:
        %h3.center-block
          - if current_user != nil
            = current_user.bitcoin_address
            %table.qr-code
              - @qr.modules.each_index do |x|
                %tr
                  - @qr.modules.each_index do |y|
                    %td{:class => (@qr.dark?(x,y) ? 'black' : 'white')}

app/views/visitors/_transaction_history_modal.html.haml
#transactionModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span.aria-hidden
            &times;
          %span.sr-only
            Close
        %h4.modal-title Transaction History
      .modal-body
        %table.table.table-striped
          %thead
            %tr
              %th Amount
              %th Type
              %th Status
              %th Date
          %tbody#transaction-history
            - @transactions.each do |tx|
              %tr
                %td
                  = tx[:amount]
                %td
                  = tx[:address]
                %td
                  = tx[:status]
                %td
                  = time_ago_in_words(tx[:date]) + ' ago.'

app/views/visitors/_verification_modal.html.haml
#verificationModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Provably Fair
      .modal-body
        #verCont
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        
:javascript
  function showVerification(id) {
    var url = '/bets/' + id;

    $( "#verCont" ).load( url );
    $('#verificationModal').modal();
  }

app/views/visitors/bet_table.html.haml
= render :partial => "bets_table_rows"

app/views/visitors/configure.html.haml
.container
  .row
    %h3
      Secure Cold Storage Installation
    %p 
      To configure 
      we need to connect to the ONCHAIN.IO cold storage service. ONCHAIN.IO provides multi signature
      funds to secure yours and your users money.
    %p
      Create or log into your account on ONCHAIN.IO and complete the following steps.
      %ol
        %li
          Go to the funds menu and create a new fund.
        %li
          Add up to 10 people to the fund. People in the fund will have the ability to sign transactions.
        %li
          Click the send invites button.
        %li 
          Wait until all your invitees have accepted the invitations and added their public keys to the
          fund.
        %li
          You need to create an environment variable called 'master_public_keys' and set this to the value of each public key. Comma separated.
          
        %textarea.form-control
          master_public_keys=xpub69GZWTQPtwQRriHyYuYJpDgAUrHHRD8ksBbQ61QpY1CbSUrcW7udYcZ1YLuLVtSQx9xW5QApiGidDfmFVLEz4Lep3AoCGD2HQmfvXwH1GMt,xpub69GZWTQPtwQRriHyYuYJpDgAUrHHRD8ksBbQ61QpY1CbSUrcW7udYcZ1YLuLVtSQx9xW5QApiGidDfmFVLEz4Lep3AoCGD2HQmfvXwH1GMt

app/views/visitors/index.html.haml
.container
  .row{ :style => 'margin-bottom: 40px' } 
    .col-md-12.text-center
      - if current_user == nil
        %h1
          Provably Fair Bitcoin Gambling
        %h2
          Register to try BitsinoDice out for free
  .row
    .col-md-3
      #userDetails
        %dl
          %dt Name
          %dd
            %input#username.form-control{:type => "text", :value => current_user.try(:name), :readonly => "true"} 
          %dt User Id
          %dd
            %input#userid.form-control{:type => "text", :value => current_user.try(:id), :readonly => "true" } 
              
      #seeds
        %dl
          %dt Server Seed
          %dd
            %input#server-seed.form-control{:readonly => "true", :type => "text", :value => session[:server_seed]}
          %dt Client Seed
          %dd
            %input#client-seed.form-control{:type => "text"}/
    .col-md-6.well
      = form_for(@bet, html: { role: 'form', class: 'inline-form submit-once', id: 'betForm' }) do |f|
        .row
          .col-md-12
            %label Probability of winning
            %div#probability-slider.slider{ style: 'width: 100%' }
            %input#start-prob{ type: 'hidden', value: @bet.game }
        .row{ style: 'margin-top:20px' }
          .col-md-12
            %label Amount of Bet.
            %div#amount-slider.slider{ style: 'width: 100%' }
            %input#range{ type: 'hidden', value: @data_slider_range}
            = f.hidden_field :amount, id: 'amount-hidden'
        .row{ style: 'margin-top:20px' }
          .col-md-3
            .form-group
              %label Roll Under
              = f.text_field :game, class: 'form-control', readonly: true, value: '49.50', id: 'roll-prob'
              = f.hidden_field :rolltype
              = f.hidden_field :client_seed, id: 'client-seed-form'
          .col-md-3
            %label For a profit of
            %input#bet_profit.form-control{:readonly => "true", :type => "text", :value => "0"}/
          .col-md-3
            %label With probability
            %input#bet_chance.form-control{:readonly => "true", :type => "text", :value => "49.50%"}/
          .col-md-3
            %label Amount of Bet
            %input{ type: 'text', class: 'form-control input-small', readonly: "true", id: 'amount-view', placeholder: 'Amount', value: '0' } 
        .form-group{:style => "margin-top: 10px"}
          - if current_user == nil
            = f.submit 'Roll Dice', class: 'btn btn-block btn-info disabled', id: 'roll-button'
          - else 
            = f.submit 'Roll Dice', class: 'btn btn-block btn-info btn-raised', id: 'roll-button'
    .col-md-3.btc-options
      .row
        .col-md-12
          %label BTC Balance
          - if current_user != nil
            %input#balance.form-control{:type => "text", 
              :value => number_to_human(current_user.balance_as_btc, precision: 8, strip_insignificant_zeros: true), 
              :readonly => "true", "data-address" => "#{current_user.try(:address)}"} 
          - else
            %input#balance.form-control{:type => "text", :value => '0', :readonly => "true"} 
      .row{ style: 'margin-top:10px' }
        .col-md-12
          - if current_user == nil
            %button.btn.btn-primary.disabled.btn-block
              %i.mdi-action-account-balance-wallet
              Deposit
          - else 
            %button.btn.btn-primary.btn-block{"data-target" => "#depositModal", "data-toggle" => "modal"}
              %i.mdi-action-account-balance-wallet
              Deposit
      .row{ style: 'margin-top:10px' }
        .col-md-12
          - if current_user == nil
            %button.btn.btn-primary.disabled.btn-block
              %i.mdi-action-account-balance
              Cashout
          - else
            %button.btn.btn-primary.btn-block{"data-target" => "#cashoutModal", "data-toggle" => "modal"}
              %i.mdi-action-account-balance
              Cashout
          
      .row{ style: 'margin-top:10px' }
        .col-md-12
          - if current_user == nil
            %button.btn.btn-primary.disabled.btn-block
              %i.mdi-action-receipt
              Transaction History
          - else
            %button.btn.btn-primary.btn-block#transButton{"data-target" => "#transactionModal", "data-toggle" => "modal"}
              %i.mdi-action-receipt
              Transaction History
.container
  .row
    .col-md-12
      %table.table.table-striped
        %thead
          %tr
            %th Bet ID
            %th User
            %th Time
            %th Bet
            %th Payout
            %th Game
            %th Roll
            %th Profit
        %tbody#bets
          = render :partial => "bets_table_rows"

= render :partial => "deposit_modal"

= render :partial => "cashout_modal"

= render :partial => "transaction_history_modal"

= render :partial => "verification_modal"